### ISSUE TITLE
有restful API支持对流程的创建，流转等操作么？

### ISSUE THREAD

**Issue by sjqzhang** [dong-jianbin/flow-pro#3]
##### 版本号：
0.5

##### 问题描述：

有restful API支持对流程的创建，流转等操作么？
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by dong-jianbin** [comment]
这些都是基本功能，本项目时前后台完整的项目。请产考项目文档 https://flowpro.ddoogg.cn/

**Comment by sjqzhang** [comment]
群主最好能支持一下docker部署，也方便推广。
